import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import {
  ModalDispatchContext,
  ModalStateContext,
} from "src/contexts/ModalProvider";

const Home: NextPage = () => {
  const dispatch = useContext(ModalDispatchContext);
  const state = useContext(ModalStateContext);

  const handler = () => {
    dispatch &&
      dispatch({
        modalType: "Confirm",
        handleClickRightBtn: () => console.log("모달입니다."),
      });
  };

  console.log(state);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handler}>클릭</button>
    </>
  );
};

export default Home;
